[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"
evm_version = "cancun"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@pendle-core-v2/=lib/pendle-core-v2-public/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config